### ISSUE TITLE
地图一直在闪

### ISSUE THREAD

**Issue by style6** [d380025303/ha_gaode#1]

**Comment by d380025303** [comment]
能否提供更全面的信息 

是高德地图一直在闪, 还是操作窗口在闪?

能否F12提供一下console日志

**Comment by style6** [comment]
![2023530-93933](https://github.com/d380025303/ha_gaode/assets/47061418/19aa5042-cfb9-4cad-93a6-a56d3937e8d1)

**Comment by style6** [comment]
https://github.com/d380025303/ha_gaode/assets/47061418/baf0d366-8a3c-4d70-a569-8ed3e5af7bd0
