### ISSUE TITLE
高德坐标飘移

### ISSUE THREAD

**Issue by jjss520** [d380025303/ha_gaode#2]
加入对高德坐标的支持的

**Comment by d380025303** [comment]
啥意思？意思是你的GPS坐标已经是高德坐标了，不应该再转换了？

**Comment by jjss520** [comment]
> 啥意思？意思是你的GPS坐标已经是高德坐标了，不应该再转换了？

对，我有几个设备本身就是高德坐标了，好像用的典心地图就飘移，位置不对

**Comment by d380025303** [comment]
理解  地图内部会自动转换一次GPS坐标，所以坐标偏移了，后续我增加配置让某些device_tracker不转换

**Comment by jjss520** [comment]
> 理解 地图内部会自动转换一次GPS坐标，所以坐标偏移了，后续我增加配置让某些device_tracker不转换

好的

**Comment by d380025303** [comment]
> > 理解 地图内部会自动转换一次GPS坐标，所以坐标偏移了，后续我增加配置让某些device_tracker不转换
> 
> 好的

https://github.com/d380025303/ha_gaode_server/releases/tag/v4.0 此版本增加此特性

**Comment by d380025303** [comment]
> > 理解 地图内部会自动转换一次GPS坐标，所以坐标偏移了，后续我增加配置让某些device_tracker不转换
> 
> 好的

https://github.com/d380025303/ha_gaode_server/releases/tag/v4.0 此版本增加此特性
