### ISSUE TITLE
无法识别位置和编辑按钮没反应

### ISSUE THREAD

**Issue by WalterDSU** [d380025303/ha_gaode#3]
HA 2023.6.1
集成V3.0
出现下面错误.

![image](https://github.com/d380025303/ha_gaode/assets/91654066/f2535a8f-935e-4e05-9165-1d7091f8e23f)

**Comment by d380025303** [comment]
清理一下浏览器缓存看看

**Comment by d380025303** [comment]
F12 看下有没有相关的报错

**Comment by jpcugv** [comment]
我也是点击编辑或者操作没有反应，按F12也无反应，不会排查错误

**Comment by d380025303** [comment]
经过测试没有点击编辑没有反应的问题, 此版本需要与 https://github.com/d380025303/ha_gaode_server/releases/tag/v3.0 此3.0版本一起配合使用, 是否没有升级ha_gaode_server?

**Comment by d380025303** [comment]
> 我也是点击编辑或者操作没有反应，按F12也无反应，不会排查错误

经过测试没有点击编辑没有反应的问题, 此版本需要与 https://github.com/d380025303/ha_gaode_server/releases/tag/v3.0 此3.0版本一起配合使用, 是否没有升级ha_gaode_server?

**Comment by d380025303** [comment]
> 我也是点击编辑或者操作没有反应，按F12也无反应，不会排查错误

经测试本地没有出现问题
有两个方向可以实验一下:

1. 使用 https://github.com/d380025303/ha_gaode_server/releases/tag/v3.0 这个版本配合使用看是否有问题

1.  提供一下出错zone实体的属性, 看是否是因为 gcj02_longitude, gcj02_latitude 这两个值错误引起的, 这两个值为字符串型的高德经纬度坐标

**Comment by d380025303** [comment]
无回应 本地未复现
