### ISSUE TITLE
2023.07.21 hacs前端中搜不到

### ISSUE THREAD

**Issue by fxonei** [d380025303/ha_gaode#4]
2023.07.21 hacs前端中搜不到
下载存储库中搜不到dxgaodemapcard  是我哪里操作有问题吗？  我这边下载其他的都是正常的，
 我是想通过hacs下载后续可以及时更新

**Comment by d380025303** [comment]
我这边测试搜索的到呢，需要选择前端的选项

![1](https://github.com/d380025303/ha_gaode/assets/31104430/3be10c6c-8257-4bf0-8584-7590a7989df7)

**Comment by d380025303** [comment]
非bug
关闭
